<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260226105418 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE daily_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, hydration_done BOOLEAN DEFAULT false NOT NULL, sleep_done BOOLEAN DEFAULT false NOT NULL, steps_done BOOLEAN DEFAULT false NOT NULL, nutrition_done BOOLEAN DEFAULT false NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D0D8EA9A76ED395 ON daily_log (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_date ON daily_log (user_id, date)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, work_email VARCHAR(255) DEFAULT NULL, login_password VARCHAR(20) DEFAULT NULL, is_admin BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649CF69075B ON "user" (work_email)');
        $this->addSql('CREATE UNIQUE INDEX unique_name ON "user" (name)');
        $this->addSql('CREATE TABLE weekly_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, week_start_date DATE NOT NULL, activity_done BOOLEAN DEFAULT false NOT NULL, social_done BOOLEAN DEFAULT false NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98B56700A76ED395 ON weekly_log (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_week ON weekly_log (user_id, week_start_date)');
        $this->addSql('ALTER TABLE daily_log ADD CONSTRAINT FK_8D0D8EA9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE weekly_log ADD CONSTRAINT FK_98B56700A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('ALTER TABLE daily_log DROP CONSTRAINT FK_8D0D8EA9A76ED395');
        $this->addSql('ALTER TABLE weekly_log DROP CONSTRAINT FK_98B56700A76ED395');
        $this->addSql('DROP TABLE daily_log');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE weekly_log');
    }
}
